### ISSUE TITLE
Refactor back-end files

### ISSUE THREAD

**Issue by ASimpleFox** [Husky-Coding-Project/club-website#27]
Refactor the back-end files so that not everything is stuck in the `end-points` file. Preferably split it into either one file for each endpoint in a folder for each category (leads, projects, events), or one file for each category.

Make sure the front-end is aware of the refactoring changes so they can update their files (or we can do it for them, it's just a matter of fixing import paths).

**Comment by rachjiang** [comment]
Claiming. Working on issue now

**Comment by rachjiang** [comment]
Hello, I've refactored the back-end files from end_points.js locally and would like to push up the changes for review. This is my first open source contribution, so please let me know if there's anything I should look out for :)

**Comment by ASimpleFox** [comment]
Hey @rachjiang! We're actually not an open-source project. This is the club website for an RSO in the University of Washington. But if you'd like I'd be happy to check out the changes you've made!

**Comment by rachjiang** [comment]
Ah, sorry for misunderstanding! This issue appeared on goodfirstissues.com so I just assumed it was an OPC. I'd be happy to share the changes anyway in case they happen to be the solution you were looking for! If this sounds good to you, please let me know if you'd like me to create a pull request (just would need access to push the branch up if you and your team are comfortable with that). If not, no pressure and no worries!

**Comment by ASimpleFox** [comment]
@rachjiang Hey! Sorry for the late response (holiday season haha), I've sent you an invite to the project so you can push up a PR. Note that it's best to make a **Fork** of the repository, push your changes there, then create a Pull Request. We'll take a look at it ASAP afterwards 👍 

TY for your patience!

**Comment by rachjiang** [comment]
No worries at all and happy holidays! 

I've forked the repo and created a pull request under a branch called 'endpoints'. Thank you for inviting me to contribute! Open to any feedback.
